models/Userdb.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "pms_user".
 *
 * @property integer $user_id
 * @property string $username
 * @property string $password
 * @property integer $entity_id
 * @property integer $access_level
 * @property integer $status_id
 *
 * @property PmsBookoutReturn[] $pmsBookoutReturns
 * @property PmsCheckInOut[] $pmsCheckInOuts
 * @property PmsGuest[] $pmsGuests
 * @property PmsRestaurantBooking[] $pmsRestaurantBookings
 * @property PmsRoomBooking[] $pmsRoomBookings
 * @property PmsEntity $entity
 */
class Userdb extends \yii\db\ActiveRecord implements \yii\web\IdentityInterface
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pms_user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'password','access_level', 'status_id'], 'required'],
            [['entity_id', 'access_level', 'status_id'], 'integer'],
            [['username', 'password'], 'string', 'max' => 50],
            [['entity_id'], 'exist', 'skipOnError' => true, 'targetClass' => Entity::className(), 'targetAttribute' => ['entity_id' => 'entity_id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'user_id' => Yii::t('app', 'User ID'),
            'username' => Yii::t('app', 'Username'),
            'password' => Yii::t('app', 'Password'),
            'entity_id' => Yii::t('app', 'Entity ID'),
            'access_level' => Yii::t('app', 'Access Level'),
            'status_id' => Yii::t('app', 'Status ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBookoutReturns()
    {
        return $this->hasMany(BookoutReturn::className(), ['user_id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCheckInOuts()
    {
        return $this->hasMany(CheckInOut::className(), ['user_id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGuests()
    {
        return $this->hasMany(Guest::className(), ['user_id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRestaurantBookings()
    {
        return $this->hasMany(RestaurantBooking::className(), ['user_id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRoomBookings()
    {
        return $this->hasMany(RoomBooking::className(), ['user_id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEntity()
    {
        return $this->hasOne(Entity::className(), ['entity_id' => 'entity_id']);
    }
	
	public function getRole()
    {
        return $this->hasOne(Role::className(), ['role_id' => 'access_level']);
    }
	
	public function getPerson(){
		return $this->hasOne(Person::className(), ['entity_id' => 'entity_id']);
	}
    
	public function getStatusType(){
		return $this->hasOne(StatusType::className(), ['status_id' => 'status_id']);
	}
	
	
	public static function findIdentity($id){
		return static::findOne($id);
	}

	public static function findIdentityByAccessToken($token, $type = null){
		throw new NotSupportedException();//I don't implement this method because I don't have any access token column in my database
	}

	public function getId(){
		return $this->user_id;
	}

    public function getAuthKey(){
		return $this->access_level;//Here I return a value of my authKey column
	}
 
	public function validateAuthKey($authKey){
		return $this->access_level === $authKey;
	}
	public static function findByUsername($username){
		return self::findOne(['username'=>$username]);
	}

	public function validatePassword($password){
		return $this->password === $password;
	}
}

views/admin/dashboard.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Admin Dashboard';
?>
    <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                  <h3><i class="fa fa-users"></i> 
    <?= Html::encode($this->title) ?></h3>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                      <div class="profile_img">
                        <div id="crop-avatar">
                          <!-- Current avatar -->
                          <img class="img-responsive avatar-view" src="../web/admin/images/<?= Yii::$app->user->identity->person->photo ?>" alt="Admin Image">
                        </div>
                      </div>
                <h2><?= Yii::$app->user->identity->person->surname.' '.Yii::$app->user->identity->person->first_name ?></h2>

                      <ul class="list-unstyled user_data">
                        <li><i class="fa fa-map-marker user-profile-icon"></i> San Francisco, California, USA
                        </li>

                        <li>
                          <i class="fa fa-briefcase user-profile-icon"></i> Software Engineer
                        </li>

                        <li class="m-top-xs">
                          <i class="fa fa-external-link user-profile-icon"></i>
                          <a href="http://www.kimlabs.com/profile/" target="_blank">www.kimlabs.com</a>
                        </li>
                      </ul>

                    </div>
                  </div>
                </div>
              </div>
            </div>

views/admin/folio.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\SearchGuest */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Folio';
$this->params['breadcrumbs'][] = $this->title;
?>
    <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                  <div class="x_title">
                  <h3><i class="fa fa-folder-open"></i> 
    <?= Html::encode($this->title) ?></h3>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
<div class="guest-index">
<h3>Credit</h3>
<div class="table-responsive">
                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>Entity ID</th>
                          <th>Registration Date</th>
                          <th>User ID</th>
                          <th>Status ID</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td></td>
                          <td></td>
                          <td></td>
                          <td></td>
                        </tr>
                            </tbody>
                            </table>
                            </div>

<h3>Debit</h3>
<div class="table-responsive">
                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>Entity ID</th>
                          <th>Registration Date</th>
                          <th>User ID</th>
                          <th>Status ID</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td></td>
                          <td></td>
                          <td></td>
                          <td></td>
                        </tr>
                            </tbody>
                            </table>
                            </div>
</div>
</div>
</div>
</div>
</div>

views/admin/records.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\SearchGuest */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Records';
$this->params['breadcrumbs'][] = $this->title;
?>
    <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                  <div class="x_title">
                  <h3><i class="fa fa-book"></i> 
    <?= Html::encode($this->title) ?></h3>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
<div class="guest-index">

                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>Entity ID</th>
                          <th>Registration Date</th>
                          <th>User ID</th>
                          <th>Status ID</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td></td>
                          <td></td>
                          <td></td>
                          <td></td>
                        </tr>
                            </tbody>
                            </table>
</div>
</div>
</div>
</div>
</div>

views/admin/reports.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\SearchGuest */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Reports';
$this->params['breadcrumbs'][] = $this->title;
?>
    <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                  <div class="x_title">
                  <h3><i class="fa fa-bar-chart"></i> 
    <?= Html::encode($this->title) ?></h3>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
<div class="col-md-12">
<div class="col-md-4"><h3>Front Office</h3>
<li><?php echo Html::a(' Arrival Departure & Stay Over Report', ['/room/arrival-departure-report']) ?></li>
<li><?php echo Html::a(' Guest Inhouse Report', ['/room/guest-inhouse-report']) ?></li>
<li><?php echo Html::a(' Guest Ledger Report', ['/room/guest-ledger-report']) ?></li>
<li><?php echo Html::a(' Room Availibility Report', ['/room/room-availability-report']) ?></li>
<li><?php echo Html::a(' Room Chart', ['/room/room-chart']) ?></li>
</div>
<div class="col-md-4"><h3>Reservations</h3>
                        <li><?php echo Html::a(' Arrival List Report', ['/reservations/arrival-list-report']) ?></li>
                        <li><?php echo Html::a(' Availability Chart', ['/reservations/availability-chart']) ?></li>
                        <li><?php echo Html::a(' Monthly Inventory Report', ['/reservations/monthly-inventory-report']) ?></li>
                        <li><?php echo Html::a(' Reservation Report', ['/reservations/reservation-report']) ?></li>
</div>
<div class="col-md-4"><h3>Rooms</h3>
                        <li><?php echo Html::a(' Room Status Report', ['/room/room-status-report']) ?></li>
                        <li><?php echo Html::a(' Company Wise Room Report', ['/room/company-wise-room-report']) ?></li>
                        <li><?php echo Html::a(' Guest Wise Room Report', ['/room/guest-wise-room-report']) ?></li>
                        <li><?php echo Html::a(' Room History Report', ['/room/room-history-report']) ?></li>
                        <li><?php echo Html::a(' Room Statistics', ['/room/room-statistics-report']) ?></li>
                        <br>
</div>
</div>

<div class="col-md-12">
<div class="col-md-4"><h3>Night Audit</h3>
<li><?php echo Html::a(' Daily Flash Report', ['/reservations/availability-chart']) ?></li>
<li><?php echo Html::a(' Daily Summary Report', ['/reservations/availability-chart']) ?></li>
<li><?php echo Html::a(' Night Audit Report', ['/reservations/availability-chart']) ?></li>
<li><?php echo Html::a(' Room Rent Variation Report', ['/reservations/availability-chart']) ?></li>
</div>
<div class="col-md-4"><h3>Direct Billing & Company</h3>
<li><?php echo Html::a(' City Ledger Report', ['/reservations/availability-chart']) ?></li>
<li><?php echo Html::a(' Direct Bill Register Report</li>', ['/reservations/availability-chart']) ?></div>
<div class="col-md-4"><h3>Group Booking</h3>
<li><?php echo Html::a(' Assigned Room Report', ['/reservations/availability-chart']) ?></li>
<li><?php echo Html::a(' Group Arrival List', ['/reservations/availability-chart']) ?></li>
<li><?php echo Html::a(' Group In-house Report', ['/reservations/availability-chart']) ?></li>
<li><?php echo Html::a(' Group Outstanding Report', ['/reservations/availability-chart']) ?></li>
<br>
</div>
</div>
</div>
</div>
</div>
</div>