models/Person.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "pms_person".
 *
 * @property integer $person_id
 * @property string $surname
 * @property string $first_name
 * @property integer $entity_id
 *
 * @property PmsEntity $entity
 */
class Person extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pms_person';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['surname', 'first_name'], 'required'],
            [['entity_id'], 'integer'],
            [['surname', 'first_name'], 'string', 'max' => 50],
            [['entity_id'], 'exist', 'skipOnError' => true, 'targetClass' => Entity::className(), 'targetAttribute' => ['entity_id' => 'entity_id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'person_id' => Yii::t('app', 'Person ID'),
            'surname' => Yii::t('app', 'Surname'),
            'first_name' => Yii::t('app', 'First Name'),
            'entity_id' => Yii::t('app', 'Entity ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEntity()
    {
        return $this->hasOne(Entity::className(), ['entity_id' => 'entity_id']);
    }
	public function getAddress()
    {
        return $this->hasOne(Address::className(), ['entity_id' => 'entity_id']);
    }
	public function getTelephones()
    {
        return $this->hasOne(Telephone::className(), ['entity_id' => 'entity_id']);
    }
	public function getPersonString()
    {
        return $this->surname . ' '. $this->first_name;
    }
	public function getEmails()
    {
        return $this->hasOne(Email::className(), ['entity_id' => 'entity_id']);
    }
}

models/RoomBooking.php
<?php

namespace app\models;

use Yii;
use app\tenttacularclass\EntityBehaviour;
use app\tenttacularclass\FolioPosting;

/**
 * This is the model class for table "pms_room_booking".
 *
 * @property integer $booking_id
 * @property integer $room_id
 * @property integer $guest_id
 * @property integer $tariff_id
 * @property integer $amount_paid
 * @property integer $time_in
 * @property integer $time_out
 * @property integer $user_id
 * @property integer $status_id
 *
 * @property PmsGuest $guest
 * @property PmsUser $user
 * @property PmsRoom $room
 * @property PmsRoomTariff $tariff
 */
class RoomBooking extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
	public $isNotNew;
	public $reciptId ;
	public $amountDue;
    public static function tableName()
    {
        return 'pms_room_booking';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
			[[  'amount_paid', 'status_id'], 'required'],
			[[  'isNotNew'], 'safe'],
            [['amount_paid'], 'integer'],
            [['room_id', 'entity_id', 'tariff_id', 'amount_paid', 'user_id', 'status_id'], 'integer'],
			[['time_in', 'time_out','number_of_nights'], 'safe'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => Userdb::className(), 'targetAttribute' => ['user_id' => 'user_id']],
            [['room_id'], 'exist', 'skipOnError' => true, 'targetClass' => Room::className(), 'targetAttribute' => ['room_id' => 'room_id']],
            
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'booking_id' => 'Booking ID',
            'room_id' => 'Room No.',
            'entity_id' => 'Entity ID',
            'tariff_id' => 'Tariff ID',
            'amount_paid' => 'Amount Paid',
            'time_in' => 'Check-in',
            'time_out' => 'Check-out',
            'user_id' => 'Admin',
            'status_id' => 'Guest Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGuest()
    {
        return $this->hasOne(Guest::className(), ['entity_id' => 'entity_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(Userdb::className(), ['user_id' => 'user_id']);
    }
	public function getperson()
    {
        return $this->guest->person;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRoom()
    {
        return $this->hasOne(Room::className(), ['room_id' => 'room_id']);
    }
	public function getStatus()
    {
        return $this->hasOne(StatusType::className(), ['status_id' => 'status_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTariff()
    {
        return $this->hasOne(RoomTariff::className(), ['tariff_id' => 'tariff_id']);
    }
	
	public function getEntity()
    {
        return $this->hasOne(Entity::className(), ['entity_id' => 'entity_id']);
    }
	
	public function behaviors()
	{
      return [
          EntityBehaviour::className(),
          FolioPosting::className(),
      ];
		
	}
	
}

controllers/RoomBookingController.php
<?php

namespace app\controllers;

use Yii;
use app\models\RoomBooking;
use app\models\Email;
use app\models\Address;
use app\models\Telephone;
use app\models\Person;
use app\models\States;
use app\models\Entity;

use app\models\Countries;
use app\models\StatusType;
use app\models\Guest;
use app\models\Room;
use app\models\ReciptRelationship;
use app\models\Recipt;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Expression;

/**
 * RoomBookingController implements the CRUD actions for RoomBooking model.
 */
class RoomBookingController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all RoomBooking models.
     * @return mixed
     */
    public function actionIndex()
    {
        $model = RoomBooking::find()->all();

        return $this->render('index', [
            'model' => $model,
        ]);
    }

    /**
     * Displays a single RoomBooking model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
		$model = new ReciptRelationship;
		$reciptmodel = new Recipt;
		$roomBookingModel = new RoomBooking;
		$fetchsenarioId = $model->find()->where(['recipt_id'=>$id])->one();
		$fetchReceiptDetails = $reciptmodel->find()->where(['recipt_id'=>$id])->one();
		$getSenarioId = $fetchsenarioId->senarior_id;
		$fetchRoomBookingDetails = $roomBookingModel->findOne($getSenarioId);
		$timeIn = new \DateTime($fetchRoomBookingDetails->time_in);
		$timeOut = new \DateTime($fetchRoomBookingDetails->time_out);
		$interval = date_diff($timeIn, $timeOut);
		$totalDays = $interval->format('%a');
		$getTariff = $fetchRoomBookingDetails->room->roomTariff->tariff;
		$amountDue = $totalDays * $getTariff *1.20;
        return $this->render('view', [
            'model' => $fetchsenarioId,
			'getRoomBookingDetails' => $fetchRoomBookingDetails,
			'getReceiptDetails' => $fetchReceiptDetails,
			'amountDue' => $amountDue
			
        ]);
    }

    /**
     * Creates a new RoomBooking model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new RoomBooking();
        $personModel = new Person();
        $emailModel = new Email();
        $telephoneModel = new Telephone();
        $addressModel = new Address();
        $statesModel = new States();
        $countriesModel = new Countries();
        $statusTypeModel = new StatusType();
        $guestModel = new Guest();
        $entityModel = new Entity();
        $receiptModel = new Recipt();
        $ReciptRelationshipModel = new ReciptRelationship();
		//$model->isNotNew = false;
		
		// check to make sure no form is empty  if valid create a new entity id based on specifications 
        if ($model->load(Yii::$app->request->post()) && $personModel->load(Yii::$app->request->post()) && $guestModel->load(Yii::$app->request->post()) && $emailModel->load(Yii::$app->request->post()) && $telephoneModel->load(Yii::$app->request->post())  && $addressModel->load(Yii::$app->request->post())  && $model->validate() && $personModel->validate() && $emailModel->validate() && $telephoneModel->validate()  && $addressModel->validate() && $guestModel->validate() ) {
			$timeIn = new \DateTime($model->time_in);
			$timeOut = new \DateTime($model->time_out);
			$interval = date_diff($timeIn, $timeOut);
			$model->number_of_nights = (int)$interval->format('%d days');
			$dateNow = new Expression('NOW()'); // use for the time gueest was created 
			$userId = Yii::$app->user->identity->id;

			//assing entity id to all entity component
			$guestModel->entity_id = $model->entityIds;//entityModelId;
			$guestModel->registration_date = $dateNow;
			$guestModel->user_id = $userId;
			$guestModel->save(false);// save the data for guest in the database 
			$entityId = $guestModel->entity_id ;

			// assing relevat ids eg like guest id 
			$personModel->entity_id = $entityId;
			$emailModel->entity_id = $entityId;
			$telephoneModel->entity_id = $entityId;
			$addressModel->entity_id = $entityId;
			$model->user_id = $userId;
			$model->entity_id = $entityId;
			$model->tariff_id = 1; // take not change room tarrrif id to the right content 

			// save data into the db

			$personModel->save();
			$emailModel->save();
			$telephoneModel->save();
			$addressModel->save();


			//select room to update status
			$roomModel = Room::findOne($model->room_id);
			// make change of status based on status type 
			$selectStatusType = $statusTypeModel->find()->where(['status_title'=>'occupied'])->one();
			$roomModel->status = $selectStatusType->status_id;
			$roomModel->save();
			$model->save(false);
			/*
				/// insert value into the receipt table
				$receiptModel->receipt_issue_date = new Expression('NOW()');
				$receiptModel->recipt_number =rand(3009,10000000);
				$receiptModel->amount = $model->amount_paid ;
				$receiptModel->save();
				// create a recipt relationship
				$ReciptRelationshipModel->recipt_id = $receiptModel->recipt_id;
				$ReciptRelationshipModel->senarior_id = $model->booking_id;
				$ReciptRelationshipModel->senarior_type = 'roombooking';
				$ReciptRelationshipModel->save();       			
				*/
			return $this->redirect(['view', 'id' => $model->reciptId]);
			
			
		} else {
            return $this->renderAjax('create', [
                'model' => $model,
				'personModel' => $personModel,
        		'emailModel' => $emailModel,
        		'telephoneModel' => $telephoneModel,
        		'addressModel' => $addressModel,
        		'statesModel' => $statesModel,
        		'countriesModel' => $countriesModel,
        		'statusTypeModel' => $statusTypeModel,
        		'guestModel' => $guestModel,
            ]);
        }
    }

    /**
     * Updates an existing RoomBooking model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->booking_id]);
        } else {
            return $this->renderAjax('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing RoomBooking model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUnbook($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->booking_id]);
        } else {
            return $this->renderAjax('unbook', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing RoomBooking model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
	
	
    /**
     * Finds the RoomBooking model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return RoomBooking the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = RoomBooking::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
	
	
}

views/room-booking/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use app\models\StatusType;
use kartik\depdrop\DepDrop;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\RoomBooking */
/* @var $form yii\widgets\ActiveForm */

$id = $_GET['id'];
?>

<div class="room-booking-form">

    <?php $form = ActiveForm::begin(); ?>
	

    <?= $form->field($personModel, 'surname')->textInput(['maxlength' => true]) ?>
	
	<?= $form->field($personModel, 'first_name')->textInput(['maxlength' => true]) ?>

	
	<?= $form->field($emailModel, 'address')->textInput(['maxlength' => true]) ?>
	
	<?= $form->field($telephoneModel, 'number')->textInput(['maxlength' => true]) ?>
	
	<?= $form->field($addressModel, 'address')->textInput(['maxlength' => true]) ?>
	
	<?= $form->field($addressModel, 'country_id')->dropDownList(ArrayHelper::map($countriesModel->find()->all(), 'country_id', 'country_name'), ['id'=>'countryId']);?>


	<?= $form->field($addressModel, 'state_id')->widget(DepDrop::classname(), [
		 'options' => ['id'=>'stateId'],
		 'pluginOptions'=>[
			 'depends'=>['countryId'],
			 'placeholder' => 'Select...',
			 'url' => Url::to(['/site/state'])
		 ]
	 ]);
	?>
	

    <?= $form->field($model, 'room_id')->hiddenInput(['value'=>$id])->label(false) ?>

	
    <?= $form->field($model, 'amount_paid')->textInput(['type' => 'number']) ?>
	
	<?= $form->field($model, 'time_in')->widget(DatePicker::classname(), [
							'options' => ['placeholder' => 'Check-in','id' => 'timein'],
							 'pluginOptions' => [
								 'format' => 'yyyy-mm-dd',
								 'todayHighlight' => true
									],
								
								]) 
		?>
	<?= $form->field($model, 'time_out')->widget(DatePicker::classname(), [
							'options' => ['placeholder' => 'Check-out','id' => 'timeout'],
							 'pluginOptions' => [
								'format' => 'yyyy-mm-dd',
								 'todayHighlight' => true
								 
									],
								
								]) 
		?>
	
	

    <?= $form->field($guestModel, 'status_id')->dropdownList(ArrayHelper::map($statusTypeModel->find()->all(), 'status_id', 'status_title'), array('style' => 'display:none'));?>

    <?=$form->field($model, 'status_id')->label(false)->dropdownList(ArrayHelper::map($statusTypeModel->find()->all(), 'status_id', 'status_title'));?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-danger' : 'btn btn-danger']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/room-booking/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\RoomBooking */

$this->title = 'Create Room Booking';
$this->params['breadcrumbs'][] = ['label' => 'Room Bookings', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="room-booking-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
		'personModel' => $personModel,
        'emailModel' => $emailModel,
        'telephoneModel' => $telephoneModel,
        'addressModel' => $addressModel,
        'statesModel' => $statesModel,
        'countriesModel' => $countriesModel,
        'statusTypeModel' => $statusTypeModel,
        'guestModel' => $guestModel,
    ]) ?>

</div>

views/room-booking/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\StatusType;
use kartik\datetime\DateTimePicker;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Room Booking';
$this->params['breadcrumbs'][] = $this->title;
?>
  <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
    <h3><i class="fa fa-calendar"></i> <?= Html::encode($this->title) ?></h3>
                    <div class="clearfix"></div>
    </div>
                  <div class="x_content">
<div class="room-booking-index">

  <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                      <thead>
                        <tr>

							<th>SN</th>
                          	<th>Guest Name</th>
							<th>Room</th>
                          	<th>Amount Paid</th>
                          	<th>Check-in</th>
                          	<th>Check-out</th>
                          	<th>Status</th>
	  						<th>Action</th>

                        </tr>
                      </thead>
                      <tbody>
              <?php $i=1; foreach($model as $k => $v){?>

                        <tr>

                          </td>

                          	<td><?php echo  $i;?></td>
							<td><?php echo  $v['person']['surname'].' '. $v['person']['first_name'];?></td>
							<td><?php echo  $v['room']['room_number'];?></td>
							<td><?php echo  $v['amount_paid'];?></td>
							<td><?php echo  $v['time_in'];?></td>
							<td><?php echo  $v['time_out'];?></td>
							<td><?php echo  $v['status']['status_title'];?></td>
	  						<td><i class="fa fa-eye hvr-bounce-in"></i>&nbsp;&nbsp;<i class="fa fa-pencil hvr-bounce-in"></i>
                        </tr>
                            <?php $i++; }?>
                            </tbody>
                            </table>
</div>
</div>
</div>
</div>
</div>

views/room-booking/unbook.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\RoomBooking */

$this->title = 'Unbook Room: ' . $model->booking_id;
?>
<div class="room-booking-unbook">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/room-booking/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\RoomBooking */

$this->title = 'Update Room Booking: ' . $model->booking_id;
$this->params['breadcrumbs'][] = ['label' => 'Room Bookings', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->booking_id, 'url' => ['view', 'id' => $model->booking_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="room-booking-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/room-booking/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\RoomBooking */


?>
<div class="room-booking-view">

    
    

    <div class="">
            
            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12">
                <div class="x_panel">
                  
                  <div class="x_content">

                    <section class="content invoice">
                      <!-- title row -->
                      <div class="row">
                        <!-- /.col -->
                      </div>
                      <!-- info row -->
                      <div class="row invoice-info">
                        <div class="col-sm-4 invoice-col">
                          <address>
                                          <strong>DBI Guest House</strong>
                                          <strong>Iron Admin, Inc. </strong>
                                          <br>795 Freedom Ave, Suite 600
                                          <br>Lagos Nigeria
                                          <br>Phone: 1 (804) 123-9876
                                          <br>Email: dbiguestadmin.com
                                      </address>
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                          To
                          <address>
                                          <strong><?=$getRoomBookingDetails->person->surname.' '. $getRoomBookingDetails->person->first_name;?> <?=$getRoomBookingDetails->number_of_nights;?></strong>
                                          <br>Address: <?=$getRoomBookingDetails->person->address->address;?>
                                          <br>State/Country: <?='('.$getRoomBookingDetails->person->address->state->state_name.') '.$getRoomBookingDetails->person->address->country->country_name;?>
                                          <br>Phone: <?=$getRoomBookingDetails->person->telephones->number;?>
                                          <br>Email: <?=$getRoomBookingDetails->person->emails->address;?>
                                      </address>
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                          <b>Receipt  No #<?=$getReceiptDetails->recipt_number;?></b>
                          <br>
                          
                          <b>Payment Due:</b> <?=$getReceiptDetails->receipt_issue_date;?>
                          <br>
                          <b>Account:</b> 968-34567
                        </div>
                        <!-- /.col -->
                      </div>
                      <!-- /.row -->

                      <!-- Table row -->
                      <div class="row">
                        <div class="col-xs-12 table">
                          <table class="table table-striped">
                            <thead>
                              <tr>
                                <th>SN</th>
                                <th>Room No.</th>
                                <th>Product</th>
                                <th>Serial #</th>
                                <th>Description</th>
                                <th>Subtotal</th>
                              </tr>
                            </thead>
                            <tbody>
                            
                              <tr>
                                <td>1</td>
                                <td><?=$model->senarior->room->room_number ;?></td>
                                <td>Room Booking </td>
								  <td><?=$model->senarior->time_in ;?></td>
								 <td><?=$model->senarior->time_out ;?></td>
                                <td>N<?=$model->recipt->amount ;?></td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                        <!-- /.col -->
                      </div>
                      <!-- /.row -->

                      <div class="row">
                        <!-- accepted payments column -->
                        <div class="col-xs-6">
                          
                        </div>
                        <!-- /.col -->
                        <div class="col-xs-6">
                          <p class="lead">Amount Due <?=$amountDue;?></p>
                          <div class="table-responsive">
                            <table class="table">
                              <tbody>
                                <tr>
                                  <th style="width:50%">Subtotal:</th>
                                  <td><?=$model->recipt->amount ;?></td>
                                </tr>
                                <tr>
                                  <th>Service charge (10%)</th>
                                  <td>N<?=($tenper=$model->recipt->amount*10)/100 ;?></td>
                                </tr>
                                <tr>
                                  <th>VAT(5%):</th>
                                  <td>N<?=($tenper=$model->recipt->amount*5)/100 ;?></td>
                                </tr>
								  <tr>
                                  <th>consumption(5%):</th>
                                  <td>N<?=($tenper=$model->recipt->amount*5)/100 ;?></td>
                                </tr>
                                <tr>
                                  <th>Total:</th>
                                  <td>N<?=$model->recipt->amount*1.20 ;?></td>
                                </tr>
                              </tbody>
                            </table>
                          </div>
                        </div>
                        <!-- /.col -->
                      </div>
                      <!-- /.row -->

                      <!-- this row will not appear when printing -->
                      <div class="row no-print">
                        <div class="col-xs-12">
                          <button class="btn btn-primary pull-right" style="margin-right: 5px;" onclick="window.print();"><i class="fa fa-print"></i> Print</button>
                          
                        </div>
                      </div>
                    </section>
                  </div>
                </div>
              </div>
            </div>
          </div>

</div>