models/Entity.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "pms_entity".
 *
 * @property integer $entity_id
 * @property string $type
 *
 * @property PmsAddress[] $pmsAddresses
 * @property PmsClient[] $pmsClients
 * @property PmsEmail[] $pmsEmails
 * @property PmsGuest[] $pmsGuests
 * @property PmsPerson[] $pmsPeople
 * @property PmsUser[] $pmsUsers
 * @property PmsVendor[] $pmsVendors
 */
class Entity extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pms_entity';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type','folio_id'], 'required'],
            [['type'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'entity_id' => Yii::t('app', 'Entity ID'),
            'type' => Yii::t('app', 'Type'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAddresses()
    {
        return $this->hasMany(Address::className(), ['entity_id' => 'entity_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClients()
    {
        return $this->hasMany(Client::className(), ['entity_id' => 'entity_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
	
	public function getFolios(){
		return $this->folio;	
	}
	
    public function getEmail()
    {
        return $this->hasOne(Email::className(), ['entity_id' => 'entity_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGuests()
    {
        return $this->hasOne(Guest::className(), ['entity_id' => 'entity_id']);
    }
	
	/**
     * @return \yii\db\ActiveQuery(relationship for folio to entity)
     */
	public function getFolio2()
    {
        return $this->hasOne(Folio::className(), ['folio_id' => 'folio_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPeople()
    {
        return $this->hasOne(Person::className(), ['entity_id' => 'entity_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasOne(User::className(), ['entity_id' => 'entity_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVendors()
    {
        return $this->hasMany(Vendor::className(), ['entity_id' => 'entity_id']);
    }
}

models/Folio.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "pms_folio".
 *
 * @property integer $folio_id
 * @property string $amount
 * @property string $creation_date
 * @property integer $status
 * @property integer $user
 *
 * @property PmsFolioCredit[] $pmsFolioCredits
 * @property PmsFolioDebit[] $pmsFolioDebits
 */
class Folio extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pms_folio';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['amount', 'creation_date', 'status', 'user'], 'required'],
            [['creation_date'], 'safe'],
            [['status', 'user'], 'integer'],
            [['amount'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'folio_id' => Yii::t('app', 'Folio ID'),
            'amount' => Yii::t('app', 'Amount'),
            'creation_date' => Yii::t('app', 'Creation Date'),
            'status' => Yii::t('app', 'Status'),
            'user' => Yii::t('app', 'User'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPmsFolioCredits()
    {
        return $this->hasMany(FolioCredit::className(), ['folio_id' => 'folio_id']);
    }
	
	public function getPmsFolioCreditsSum()
    {
        return $this->hasMany(FolioCredit::className(), ['folio_id' => 'folio_id'])->sum('amount');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPmsFolioDebits()
    {
        return $this->hasMany(FolioDebit::className(), ['folio_id' => 'folio_id']);
    }
}

models/Person.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "pms_person".
 *
 * @property integer $person_id
 * @property string $surname
 * @property string $first_name
 * @property integer $entity_id
 *
 * @property PmsEntity $entity
 */
class Person extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pms_person';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['surname', 'first_name'], 'required'],
            [['entity_id'], 'integer'],
            [['surname', 'first_name'], 'string', 'max' => 50],
            [['entity_id'], 'exist', 'skipOnError' => true, 'targetClass' => Entity::className(), 'targetAttribute' => ['entity_id' => 'entity_id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'person_id' => Yii::t('app', 'Person ID'),
            'surname' => Yii::t('app', 'Surname'),
            'first_name' => Yii::t('app', 'First Name'),
            'entity_id' => Yii::t('app', 'Entity ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEntity()
    {
        return $this->hasOne(Entity::className(), ['entity_id' => 'entity_id']);
    }
	public function getAddress()
    {
        return $this->hasOne(Address::className(), ['entity_id' => 'entity_id']);
    }
	public function getTelephones()
    {
        return $this->hasOne(Telephone::className(), ['entity_id' => 'entity_id']);
    }
	public function getPersonString()
    {
        return $this->surname . ' '. $this->first_name;
    }
	public function getEmails()
    {
        return $this->hasOne(Email::className(), ['entity_id' => 'entity_id']);
    }
}

controllers/FolioController.php
<?php

namespace app\controllers;

use Yii;
use app\models\FolioCredit;
use app\models\FolioDebit;
use app\models\Folio;
use app\models\Entity;
use app\models\RestaurantPrice;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Expression;

/**
 * RestaurantBookingController implements the CRUD actions for RestaurantBooking model.
 */
class FolioController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    
	
	public function actionIndex(){
		$folioModel = new Folio();
		$getFolioDetails = $folioModel->find()->all();
		return $this->render('index', [
            'folio' => $getFolioDetails,
        ]);
	}
 
    public function actionView($id,$entity)
    {
		$fetchEntity = Entity::findOne($entity);
		$getPersonString = $fetchEntity->people->personString;
        return $this->renderAjax('view', [
            'debit' => $this->findDebitFolioModel($id),
            'credit' => $this->findCreditFolioModel($id),
			'debitSum' => FolioDebit::find()->where(['folio_id'=>$id])->sum('amount'),
            'creditSum' => FolioCredit::find()->where(['folio_id'=>$id])->sum('amount'),
			'entity' => $fetchEntity,
        ]);
    }

   
	
     protected function findDebitFolioModel($id)
    {
        if (($model = FolioDebit::find()->where(['folio_id'=>$id])->all()) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
	
	protected function findCreditFolioModel($id)
    {
        if (($model = FolioCredit::find()->where(['folio_id'=>$id])->all()) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/folio/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use  yii\bootstrap\Modal;

/* @var $this yii\web\View */
/* @var $searchModel app\models\SearchGuest */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Folio';
$this->params['breadcrumbs'][] = $this->title;
?>
    <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
            
                <div class="x_panel">
                  <div class="x_title">
                  <h3><i class="fa fa-users"></i> 
    <?= Html::encode($this->title) ?></h3>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                  <div class="" role="tabpanel" data-example-id="togglable-tabs">
                        
                      <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#bookings" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Folio</a>
                        </li>
                        <li role="presentation" class=""><a href="#report" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false">Reports</a>
                        </li>
                      </ul>
                      <div id="myTabContent" class="tab-content">
                        <div role="tabpanel" class="tab-pane fade active in" id="bookings" aria-labelledby="home-tab">
                      
<div class="guest-index">

                    <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                      <thead>
                        <tr>

							<th>SN</th>
                          	<th>Guest Name</th>
							<th>Room</th>
                          	<th>Amount Paid</th>
                          	
                        </tr>
                      </thead>
                      <tbody>
						  <? //var_dump($folio); return false;?>
						  <?php if(!empty($folio)){ ?>
           <?php $i=1; foreach($folio as $k => $v){?>

                        <tr>

                          	<td><?php echo  $i;?></td>
							<td><?php echo !empty($v['pmsFolioCredits'])?'#'.$v['pmsFolioCreditsSum']:0;?></td>
							<td><?php echo  !empty($v['pmsFolioDebits']['amount'])?count($v['pmsFolioDredits']['amount']):0;?></td>
							
							<td>
								
							</td>

                        </tr>
                            <?php $i++; }?>
						  <?php } ?>
						  
                            </tbody>
                            </table>
</div>
</div>

                        <div role="tabpanel" class="tab-pane fade" id="report" aria-labelledby="profile-tab">
                
                        <font size="+1">
<li><?php echo Html::a(' Arrival Departure & Stay Over Report', ['/room/arrival-departure-report']) ?></li>
<li><?php echo Html::a(' Guest Inhouse Report', ['/room/guest-inhouse-report']) ?></li>
<li><?php echo Html::a(' Guest Ledger Report', ['/room/guest-ledger-report']) ?></li>
                        <li><?php echo Html::a(' Guest Wise Room Report', ['/room/guest-wise-room-report']) ?></li>
<li><?php echo Html::a(' Assigned Room Report', ['/reservations/availability-chart']) ?></li>
<li><?php echo Html::a(' Group Arrival List', ['/reservations/availability-chart']) ?></li>
<li><?php echo Html::a(' Group In-house Report', ['/reservations/availability-chart']) ?></li>
<li><?php echo Html::a(' Group Outstanding Report', ['/reservations/availability-chart']) ?></li>
                        </font>
                        </div>
</div>
</div>
</div>
</div>
</div>
</div>
<?php
//this should be put directly inside the user index page (best practice should be the last thing in the page 
Modal::begin([
            'header' =>'<h1 id="modalheader"></h1>',
            'id' => 'guestmodal',
            'size' => 'modal-lg',  
        ]);
echo "
<div id='wait'><center><img src='../web/admin/images/ajax-loader.gif' /></center></div>";
        echo "<div id='guestmodalcontent'></div>";
        Modal::end();
    ?>

views/folio/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;


?>
<div class="color-view">
<div>
	<?=$entity->people->personString; ?>
	<?=$entity->email->address; ?>
	
	<button class="pull-right btn btn-danger booking" data-url="<?php echo Url::to(['create']); ?>" >Credit Account</button>
	<button class="pull-right btn btn-danger booking" data-url="<?php echo Url::to(['create']); ?>" >Close Account</button>
	<button class="pull-right btn btn-danger booking" data-url="<?php echo Url::to(['create']); ?>" >Send to back office</button>

	</div>
    
    <table class="table table-bordered table-condensed" >
		
		
		<tbody>
			<tr>
		
			<td>
				<table class="table table-striped">
					<thead>

						<th>Date</th>
						<th>Text</th>
						<th>Amount</th>
					</thead>
				<? foreach($debit as $k => $v){ ?>
					<tr>
						<td>
							<?=$v['date_posted'];?>
						</td>
						
						<td>
							<?=$v['senario_type'];?>
						</td>
						
						<td>
							<?=$v['amount'].'('.$v['senario_id'].')' ;?>
						</td>
					</tr>
				<? } ?>
				</table>
			</td>
			<td>
				<table class="table table-striped">
					<thead>

						<th>Date</th>
						<th>Text</th>
						<th>Amount</th>
					</thead>
		
				<? foreach($credit as $k => $v){ ?>
					<tr>
						<td>
							<?=$v['date_posted'];?>
						</td>
						
						<td>
							<?=$v['senario_type'];?>
						</td>
						
						<td>
							<?=$v['amount'].'('.$v['senario_id'].')' ;?>
						</td>
					</tr>
				<? } ?>
				</table>
			</td>
		   </tr>
			<tr>
				<td>Total: <?=$debitSum; ?></td>
				<td>Total: <?=($creditSum != $debitSum and $creditSum < $debitSum )?'('.$creditSum.')':$creditSum; ?></td>
			</tr>
		</tbody>
	</table>

	 
</div>